name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Opening Release PR
        uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Checkout Repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
      - name: Install Bun
        if: ${{ steps.release.outputs.release_created }}
        uses: oven-sh/setup-bun@v2
        with:
          version: 1.2.13
      - name: Bun - Install Dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: bun install
      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: bun publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
